import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Hero from "./components/Hero";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Login from "./components/Login";
import Quote  from "./components/Quote";
import Poetry from "./components/Poetry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FFEDDB]`}
      >
        <Navbar/>
        <Hero/>
        <Login/>
        <Quote/>
        <Poetry/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}
